version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  login:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: login
    ports:
      - "8887:80"
    networks:
      - proxy
      - default
      - backend
    environment:
      NODE_ENV: "development"
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "b1c78c1e-3c88-44f4-90fa-bebc5c5dc28d"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://kaleidos-dev.vlaanderen.be/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "${MU_APPLICATION_AUTH_CLIENT_SECRET}"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "dkb_kaleidos_rol_3d"
      MU_APPLICATION_AUTH_USERID_CLAIM: "vo_id"
      DEBUG_LOG_TOKENSETS: "true"
      LOG_SINK_URL: "http://sink"
    logging: *default-logging
    labels:
      - "logging=true"
    external_links:
      - db:database

networks:
  proxy:
    external:
      name: letsencrypt_default
  backend:
    external: true
